from compressionNN import compressed_nn
from compressionNN import pruning
from compressionNN import pruning_uCWS
from compressionNN import pruning_uECSQ
from compressionNN import pruning_uPWS
from compressionNN import pruning_uUQ
from compressionNN import uCWS
from compressionNN import uECSQ
from compressionNN import uPWS
from compressionNN import uUQ
from compressionNN import nu_CWS
from compressionNN import nu_PWS
from compressionNN import nu_pruning
from compressionNN import nu_pruning_CWS
from compressionNN import nu_pruning_PWS

from compressionNN import huffman
from compressionNN import sparse_huffman
from compressionNN import sparse_huffman_only_data
